
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action copyAction;
	private global::Gtk.Action newAction1;
	private global::Gtk.Action executeAction;
	private global::Gtk.Action stopAction;
	private global::Gtk.Action newArticulo;
	private global::Gtk.Action newCategoria;
	private global::Gtk.Action refreshCategoria;
	private global::Gtk.Action refreshArticulo;
	private global::Gtk.Action newCategoria1;
	private global::Gtk.Action refreshAction;
	private global::Gtk.Action editarCat;
	private global::Gtk.Action deleteCat;
	private global::Gtk.Action newArticulo1;
	private global::Gtk.Action refreshAction1;
	private global::Gtk.Action editarArt;
	private global::Gtk.Action deleteArt;
	private global::Gtk.Action refreshArticulo1;
	private global::Gtk.Action refreshCat;
	private global::Gtk.VBox vbox5;
	private global::Gtk.Notebook notebook2;
	private global::Gtk.VBox vbox6;
	private global::Gtk.Toolbar toolbar3;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView treeviewArticulo;
	private global::Gtk.Label articulo;
	private global::Gtk.VBox vbox7;
	private global::Gtk.Toolbar toolbar4;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TreeView treeviewCategoria;
	private global::Gtk.Label categoria;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.copyAction = new global::Gtk.Action ("copyAction", null, null, "gtk-copy");
		w1.Add (this.copyAction, null);
		this.newAction1 = new global::Gtk.Action ("newAction1", null, null, "gtk-new");
		w1.Add (this.newAction1, null);
		this.executeAction = new global::Gtk.Action ("executeAction", null, null, "gtk-execute");
		w1.Add (this.executeAction, null);
		this.stopAction = new global::Gtk.Action ("stopAction", null, null, "gtk-stop");
		w1.Add (this.stopAction, null);
		this.newArticulo = new global::Gtk.Action ("newArticulo", null, null, "gtk-new");
		w1.Add (this.newArticulo, null);
		this.newCategoria = new global::Gtk.Action ("newCategoria", null, null, "gtk-new");
		w1.Add (this.newCategoria, null);
		this.refreshCategoria = new global::Gtk.Action ("refreshCategoria", null, null, "gtk-refresh");
		w1.Add (this.refreshCategoria, null);
		this.refreshArticulo = new global::Gtk.Action ("refreshArticulo", null, null, "gtk-refresh");
		w1.Add (this.refreshArticulo, null);
		this.newCategoria1 = new global::Gtk.Action ("newCategoria1", null, null, "gtk-new");
		w1.Add (this.newCategoria1, null);
		this.refreshAction = new global::Gtk.Action ("refreshAction", null, null, "gtk-refresh");
		w1.Add (this.refreshAction, null);
		this.editarCat = new global::Gtk.Action ("editarCat", null, null, "gtk-find-and-replace");
		w1.Add (this.editarCat, null);
		this.deleteCat = new global::Gtk.Action ("deleteCat", null, null, "gtk-delete");
		w1.Add (this.deleteCat, null);
		this.newArticulo1 = new global::Gtk.Action ("newArticulo1", null, null, "gtk-new");
		w1.Add (this.newArticulo1, null);
		this.refreshAction1 = new global::Gtk.Action ("refreshAction1", null, null, "gtk-refresh");
		w1.Add (this.refreshAction1, null);
		this.editarArt = new global::Gtk.Action ("editarArt", null, null, "gtk-find-and-replace");
		w1.Add (this.editarArt, null);
		this.deleteArt = new global::Gtk.Action ("deleteArt", null, null, "gtk-delete");
		w1.Add (this.deleteArt, null);
		this.refreshArticulo1 = new global::Gtk.Action ("refreshArticulo1", null, null, "gtk-refresh");
		w1.Add (this.refreshArticulo1, null);
		this.refreshCat = new global::Gtk.Action ("refreshCat", null, null, "gtk-refresh");
		w1.Add (this.refreshCat, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.notebook2 = new global::Gtk.Notebook ();
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 0;
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar3'><toolitem name='newArticulo1' action='newArticulo1'/><toolitem name='refreshArticulo1' action='refreshArticulo1'/><toolitem name='editarArt' action='editarArt'/><toolitem name='deleteArt' action='deleteArt'/></toolbar></ui>");
		this.toolbar3 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar3")));
		this.toolbar3.Name = "toolbar3";
		this.toolbar3.ShowArrow = false;
		this.vbox6.Add (this.toolbar3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.toolbar3]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeviewArticulo = new global::Gtk.TreeView ();
		this.treeviewArticulo.CanFocus = true;
		this.treeviewArticulo.Name = "treeviewArticulo";
		this.GtkScrolledWindow.Add (this.treeviewArticulo);
		this.vbox6.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.GtkScrolledWindow]));
		w4.Position = 2;
		this.notebook2.Add (this.vbox6);
		// Notebook tab
		this.articulo = new global::Gtk.Label ();
		this.articulo.Name = "articulo";
		this.articulo.LabelProp = global::Mono.Unix.Catalog.GetString ("Articulo");
		this.notebook2.SetTabLabel (this.vbox6, this.articulo);
		this.articulo.ShowAll ();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar4'><toolitem name='newCategoria1' action='newCategoria1'/><toolitem name='refreshCat' action='refreshCat'/><toolitem name='editarCat' action='editarCat'/><toolitem name='deleteCat' action='deleteCat'/></toolbar></ui>");
		this.toolbar4 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar4")));
		this.toolbar4.Name = "toolbar4";
		this.toolbar4.ShowArrow = false;
		this.vbox7.Add (this.toolbar4);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.toolbar4]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.treeviewCategoria = new global::Gtk.TreeView ();
		this.treeviewCategoria.CanFocus = true;
		this.treeviewCategoria.Name = "treeviewCategoria";
		this.GtkScrolledWindow1.Add (this.treeviewCategoria);
		this.vbox7.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.GtkScrolledWindow1]));
		w8.Position = 2;
		this.notebook2.Add (this.vbox7);
		global::Gtk.Notebook.NotebookChild w9 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.vbox7]));
		w9.Position = 1;
		// Notebook tab
		this.categoria = new global::Gtk.Label ();
		this.categoria.Name = "categoria";
		this.categoria.LabelProp = global::Mono.Unix.Catalog.GetString ("Categoria");
		this.notebook2.SetTabLabel (this.vbox7, this.categoria);
		this.categoria.ShowAll ();
		this.vbox5.Add (this.notebook2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.notebook2]));
		w10.Position = 0;
		this.Add (this.vbox5);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.refreshCategoria.Activated += new global::System.EventHandler (this.OnRefreshCategoriaActivated);
		this.newCategoria1.Activated += new global::System.EventHandler (this.OnNewCategoria1Activated);
		this.refreshAction.Activated += new global::System.EventHandler (this.OnRefreshActionActivated);
		this.editarCat.Activated += new global::System.EventHandler (this.OnEditarCatActivated);
		this.deleteCat.Activated += new global::System.EventHandler (this.OnDeleteCatActivated);
		this.newArticulo1.Activated += new global::System.EventHandler (this.OnNewArticulo1Activated);
		this.refreshAction1.Activated += new global::System.EventHandler (this.OnRefreshAction1Activated);
		this.editarArt.Activated += new global::System.EventHandler (this.OnEditarArtActivated);
		this.deleteArt.Activated += new global::System.EventHandler (this.OnDeleteArtActivated);
		this.refreshArticulo1.Activated += new global::System.EventHandler (this.OnRefreshArticulo1Activated);
		this.refreshCat.Activated += new global::System.EventHandler (this.OnRefreshCatActivated);
	}
}
