
// This file has been generated by the GUI designer. Do not modify.
namespace PMyWidget
{
	public partial class PersonaView
	{
		private global::Gtk.Table table2;
		private global::Gtk.Label Apellidos;
		private global::Gtk.Entry entryApellidos;
		private global::Gtk.Entry entryNombre;
		private global::Gtk.Label Nombre;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PMyWidget.PersonaView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "PMyWidget.PersonaView";
			// Container child PMyWidget.PersonaView.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.Apellidos = new global::Gtk.Label ();
			this.Apellidos.Name = "Apellidos";
			this.Apellidos.LabelProp = global::Mono.Unix.Catalog.GetString ("Apellidos");
			this.table2.Add (this.Apellidos);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2 [this.Apellidos]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entryApellidos = new global::Gtk.Entry ();
			this.entryApellidos.CanFocus = true;
			this.entryApellidos.Name = "entryApellidos";
			this.entryApellidos.IsEditable = true;
			this.entryApellidos.InvisibleChar = '•';
			this.table2.Add (this.entryApellidos);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.entryApellidos]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entryNombre = new global::Gtk.Entry ();
			this.entryNombre.CanFocus = true;
			this.entryNombre.Name = "entryNombre";
			this.entryNombre.IsEditable = true;
			this.entryNombre.InvisibleChar = '•';
			this.table2.Add (this.entryNombre);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.entryNombre]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.Nombre = new global::Gtk.Label ();
			this.Nombre.Name = "Nombre";
			this.Nombre.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre");
			this.table2.Add (this.Nombre);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.Nombre]));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
